apiVersion: autoscaling.kapacitystack.io/v1alpha1
kind: IntelligentHorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: kapacity-test
spec:
  maxReplicas: 10
  minReplicas: 1
  portraitProviders:
  - dynamic:
      algorithm:
        externalJob:
          job:
            type: CronJob
            cronJob:
              template:
                spec:
                  schedule: "0/30 * * * *"
                  jobTemplate:
                    spec:
                      template:
                        spec:
                          containers:
                          - name: algorithm
                            image: kapacity-algorithm:v19
                            imagePullPolicy: IfNotPresent
                            args:
                            - --tsf-model-path=/opt/kapacity/timeseries/forecasting/model
                            - --tsf-freq=10min
                            - --re-history-len=4H
                            - --re-time-delta-hours=8
                            - --re-test-dataset-size-in-seconds=3600
                            - --scaling-freq=10min
                            volumeMounts:
                            - name: model
                              mountPath: /opt/kapacity/timeseries/forecasting/model
                              readOnly: true
                          volumes:
                          - name: model
                            configMap:
                              name: kapacity-tsf-model
                          restartPolicy: OnFailure
          resultSource:
            type: ConfigMap
        type: ExternalJob
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            averageUtilization: 30
            type: Utilization
      - type: External
        external:
          metric:
            name: ready_pods_count
          target:
            type: NA
      - name: qps
        object:
          describedObject:
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            name: nginx-server
          metric:
            name: rpc
          target:
            type: Value
            value: 30
        type: Object
      portraitType: Predictive
    priority: 10
    type: Dynamic
  scaleMode: Auto
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nginx