targets:
  - workloadNamespace: kapacity-test
    workloadName: nginx
    historyLength: 48H
    metrics:
      - type: Object
        object:
          metric:
            name: nginx_ingress_controller_requests_rate
          describedObject:
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            name: nginx-server
freq: 10min
predictionLength: 3
contextLength: 7
hyperParams:
  learningRate: 0.001
  epochs: 100
  batchSize: 32